### ISSUE TITLE
(Suggestion) Player resize

### ISSUE THREAD

**Issue by tizio04** [lazy-guy/crunchyroll-enhancer#1]
Hi, it would be possible to add an option to resize the player to different sizes, when you are not in fullscreen?
I think that there is a lot of wasted space at both sides when the video is not maxed out

**Comment by lazy-guy** [comment]
I have added an option to change the player size. Make sure that you have installed the style from GitHub using Stylus extension. You can now choose from one of the following options:

1. Default
2. Max Height (Not recommended for very tall displays)
3. Max Width (Not recommended for very wide displays)

For the last two options, it is recommended to set **Max width of main content** to `No Limit`

**Comment by Dyras** [comment]
@lazy-guy at the risk of sounding like a total idiot, where do I change this, exactly?

**Comment by lazy-guy** [comment]
@Dyras , follow these steps to change this: 

1. Make sure you have [installed](https://github.com/lazy-guy/crunchyroll-enhancer/blob/master/README.md#installation) the userstyle using Stylus extension and NOT Stylish.

2. Click on the Stylus extension icon present in your browser's toolbar (or menu).

3. Now, if you have crunchyroll opened in current tab then click on the gear icon ( ![image](https://user-images.githubusercontent.com/44257523/74157087-b3b63400-4c3d-11ea-9040-f4650dd8d2c6.png) ) next to the text **Crunchyroll Enhancer**. Else, Click on manage to see the gear icon.

4. Now you should be able to see something like this :
![image](https://user-images.githubusercontent.com/44257523/74157455-51116800-4c3e-11ea-9729-c0ba90935579.png)

5. From here you should be able to configure the userstyle.

**Comment by Dyras** [comment]
I couldn't for the life of me get the gear to appear, so I reinstalled the script and it's appearing now.

Thanks for your help, and thanks for a great script!
