### ISSUE TITLE
Request: "No spoilers only" option

### ISSUE THREAD

**Issue by Dyras** [lazy-guy/crunchyroll-enhancer#2]
Greetings! I really like the "No spoilers" option in this script, and I noticed there's a setting to "Only change theme".

So I'm wondering, any chance you could bake "No spoilers" into that? I don't really care much for changing the layout of the website, I just want to avoid spoilers and to use the dark theme at the same time :)

Regardless, thanks for a great script!

**Comment by lazy-guy** [comment]
The "Hide Spoilers" options actually works even if "Only Change Theme" is set to "Yes". This is because I created "Only Change Theme" option much before most other options, like the "Hide Spoiler" one.

To prevent any more confusion, I have changed its name to "Redesigned UI".
